<?xml version="1.0"?>
<package format="3">
  <name>lidar_object_clustering</name>
  <version>0.1.0</version>
  <description>ROS 2 LiDAR ROI filtering, ground removal, voxel downsampling, Euclidean clustering, and 3D bounding boxes.</description>

  <maintainer email="117157396+myeongw002@users.noreply.github.com">myeongw002</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>vision_msgs</depend>
  <depend>pcl_conversions</depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
